language: node_js
sudo: required
node_js:
- '16'
install:
- npm ci
jobs:
  include:
  - stage: Lint
    script: npm run lint
env:
  global:
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - NODE_OPTIONS="--max-old-space-size=4096"